/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNITesting */

#ifndef _Included_JNITesting
#define _Included_JNITesting
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNITesting
 * Method:    reverseString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNITesting_reverseString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
